BRAZILIAN_STATES = ['Acre.zip',
                'Alagoas.zip',
                'Amapa.zip',
                'Amazonas.zip',
                'Bahia.zip',
                'Ceara.zip',
                'Distrito_Federal.zip',
                'Espirito_Santo.zip',
                'Goias.zip',
                'Maranhao.zip',
                'Mato_Grosso_do_Sul.zip',
                'Mato_Grosso.zip',
                'Minas_Gerais.zip',
                'Para.zip',
                'Paraiba.zip',
                'Parana.zip',
                'Pernambuco.zip',
                'Piaui.zip',
                'Rio_de_Janeiro.zip',
                'Rio_Grande_do_Norte.zip',
                'Rio_Grande_do_Sul .zip',
                'Rondonia.zip',
                'Roraima.zip',
                'Santa_Catarina.zip',
                'Sao_Paulo.zip',
                'Sergipe.zip',
                'Tocantins.zip']